### ISSUE TITLE
Yosemite Ver10.10.2

### ISSUE THREAD

**Issue by shadr00** [Chris911/iStats#16]
Hi
I am not really good ay command line, i did follow the step, but it did not work for me!!

$ sudo ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future gem install iStats

WARNING: Improper use of the sudo command could lead to data loss
or the deletion of important system files. Please double-check your
typing when using sudo. Type "man sudo" for more information.

To proceed, enter your password, or type Ctrl-C to abort.

Password:
istats all
Fetching: sparkr-0.4.1.gem (100%)
Successfully installed sparkr-0.4.1
Fetching: iStats-0.0.9.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing iStats:
	ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/include/ruby.h
Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/iStats-0.0.9 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/iStats-0.0.9/ext/osx_stats/gem_make.out

**Comment by shadr00** [comment]
Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/iStats-0.0.9 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/iStats-0.0.9/ext/osx_stats/gem_make.out

**Comment by helicine** [comment]
I was able to get iStats installed on 10.10.2 after installing the Xcode command line tools (as described in issue 11: https://github.com/Chris911/iStats/issues/11), and then installing iStats

    $ sudo xcode-select --install
    $ sudo xcodebuild --license
    $ sudo ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future gem install iStats

Afterward, I could run iStats, but had to run it via 'sudo' because both iStats and sparkr were only readable by root.  After a chmod 755 /usr/bin/istats and then adding read & execute to the appropriate files within /Library/Ruby/Gems/2.0.0/gems/iStats-0.0.9 and /Library/Ruby/Gems/2.0.0/gems/sparkr-0.4.1, I was able to get it to run under my regular account.

**Comment by ezietsman** [comment]
It looks like I can build the osx-stats module by changing the `cc` and `c++` flags to `clang` and `clang++` instead of `gcc` and `g++` in `ext/osx-stats/Makefile`.

 I don't  know enough about ruby to understand how to build and install the module manually. Is there a reason it defaults to gcc when I'm running on a Mac? (MBP, Yosemite 10.10.2). This used to work but I somehow removed or upgraded my ruby installation and iStats went with it.

**Comment by Chris911** [comment]
Hey. I have been traveling for a couple months now without a computer. I'll check this in a couple weeks.

Thanks for your contribution.

**Comment by ezietsman** [comment]
If I get some time I'll see if I can send a PR to fix it.

Safe Travels.

**Comment by ezietsman** [comment]
OK I fixed my own problem. I had another version of gcc installed that is non-standard. It was calling this version instead of a standard one.

**Comment by Chris911** [comment]
I'll try to repro the problem. Buil

**Comment by Arthur2e5** [comment]
Changing `<ruby.h>` to `<ruby-2.0.0/ruby.h>` or try adding `/System/Library/Frameworks/Ruby.framework/Versions/Current/Headers` to the include paths may help. On my 10.10, ruby.h seems to be located in `/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/ruby.h
`.
