### ISSUE TITLE
istats doesn't work on macOS High Sierra

### ISSUE THREAD

**Issue by uiiji** [Chris911/iStats#58]
sudo gem install iStats
```
Building native extensions.  This could take a while...
ERROR:  Error installing iStats:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.3.0/gems/iStats-1.5.0/ext/osx_stats
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20170926-3455-ls7i4z.rb extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/iStats-1.5.0 for inspection.
Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-17/2.3.0/iStats-1.5.0/gem_make.out

```

**Comment by huynhduy9988** [comment]
xcode-select --install

**Comment by eteanor** [comment]
@huynhduy9988 I have installed it, but it only fixes a problem with homebrew.

The problem with iStats is that it wants to use Ruby 2.0, but it was updated to 2.3 in High Sierra.

I had iStats installed before updating and here's what happens when I try to use it:
/usr/local/bin/istats: bad interpreter: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin: no such file or directory

So it just can't find Ruby.

**Comment by huynhduy9988** [comment]
I run 2 commands:
xcode-select --install
sudo gem install iStats

-> success

**Comment by uiiji** [comment]
This work!

**Comment by akid83** [comment]
Works. Thanks.
