### ISSUE TITLE
--value-only and rounded values

### ISSUE THREAD

**Issue by marekkaczkowski** [Chris911/iStats#61]
Hey Chris,
I'm working on some cool stuff (will share it soon, spoiler: you can check my empty repo 😜)
Is there a flag to get rounded values or I have to use `awk` or `bc`? Thanks!

**Comment by Chris911** [comment]
There is currently no way to get rounder values. Values that should be rounded such as fan speed, cycle count, etc. are already rounded and values that support decimals aren't which I think is the right thing to do. If you really need rounded values I think you'll have to use `awk` or `bc`as you said. 

If you're writing a program in Ruby you might be interested in https://github.com/Chris911/iStats/pull/60 that extracts the logic as a library so it can be used in other projects. You could use that instead of parsing the CLI output. I just haven't had time to review yet.

**Comment by marekkaczkowski** [comment]
That was easy 😅

![img_6835](https://user-images.githubusercontent.com/273831/32628527-7bf5404a-c596-11e7-9848-a391627d2ac0.jpg)

I'll push it to [Touch-Bar-iStats](https://github.com/marekkaczkowski/Touch-Bar-iStats) repo.

**Comment by Chris911** [comment]
That looks awesome 👍
